/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form.sanpham;

import comon.constant.sanpham.LoaiSanPham;
import comon.constant.sanpham.TrangThaiSanPham;
import dto.sanpham.AoDTO;
import dto.sanpham.ChatLieuDTO;
import dto.sanpham.MauSacDTO;
import dto.sanpham.SanPhamDTO;
import dto.sanpham.ThuongHieuDTO;
import dto.sanpham.XuatXuDTO;
import java.awt.Frame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nguyenth28
 */
public class DialogAo extends javax.swing.JDialog {

    private MauSacDTO selectedMau;
    private ChatLieuDTO selectedChatLieu;
    private ThuongHieuDTO selectedThuongHieu;
    private XuatXuDTO selectedXuatXu;

    /**
     * Creates new form DialogAo
     */
    public DialogAo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spGiaNhap = new javax.swing.JSpinner();
        spGiaBan = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spSL = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        lbMau = new javax.swing.JLabel();
        lbChatLieu = new javax.swing.JLabel();
        lbThuongHieu = new javax.swing.JLabel();
        lbXuatXu = new javax.swing.JLabel();
        lbKichCo = new javax.swing.JLabel();
        btnMau = new view.swing.Button();
        btnChatLieu = new view.swing.Button();
        btnThuongHieu = new view.swing.Button();
        btnXuatXu = new view.swing.Button();
        btnKichCo = new view.swing.Button();
        btnHuy = new view.swing.Button();
        btnLuu = new view.swing.Button();
        jLabel7 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(0, 102, 255));
        lbTitle.setText("CHI TIẾT SẢN PHẨM");
        lbTitle.setToolTipText("");

        jLabel2.setText("Mã");

        jLabel3.setText("Tên");

        jLabel4.setText("Giá nhập");

        jLabel5.setText("Giá bán");

        jLabel6.setText("Số lượng");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        jLabel12.setText("Mô tả");

        btnMau.setBackground(new java.awt.Color(0, 102, 255));
        btnMau.setForeground(new java.awt.Color(255, 255, 255));
        btnMau.setText("Màu");
        btnMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauActionPerformed(evt);
            }
        });

        btnChatLieu.setBackground(new java.awt.Color(0, 102, 255));
        btnChatLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnChatLieu.setText("Chất liệu");
        btnChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatLieuActionPerformed(evt);
            }
        });

        btnThuongHieu.setBackground(new java.awt.Color(0, 102, 255));
        btnThuongHieu.setForeground(new java.awt.Color(255, 255, 255));
        btnThuongHieu.setText("Thương hiệu");
        btnThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuongHieuActionPerformed(evt);
            }
        });

        btnXuatXu.setBackground(new java.awt.Color(0, 102, 255));
        btnXuatXu.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatXu.setText("Xuất xứ");
        btnXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatXuActionPerformed(evt);
            }
        });

        btnKichCo.setBackground(new java.awt.Color(0, 102, 255));
        btnKichCo.setForeground(new java.awt.Color(255, 255, 255));
        btnKichCo.setText("Kích cỡ");
        btnKichCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKichCoActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(255, 51, 51));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");

        btnLuu.setBackground(new java.awt.Color(0, 153, 0));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu lại");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel7.setText("Trạng thái");

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "IN ACTIVE" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnMau, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMau)
                            .addComponent(lbChatLieu)
                            .addComponent(lbThuongHieu)
                            .addComponent(lbXuatXu)
                            .addComponent(lbKichCo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lbTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(spGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(spSL, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(cbbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChatLieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThuongHieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXuatXu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKichCo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbTitle)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMau)
                            .addComponent(btnMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbChatLieu)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbThuongHieu)
                    .addComponent(btnThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbXuatXu)
                    .addComponent(btnXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKichCo)
                    .addComponent(btnKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatLieuActionPerformed
        Frame parentWindow = (Frame) SwingUtilities.windowForComponent(this);
        DialogChatLieu dialog = new DialogChatLieu(parentWindow, true);
        dialog.setVisible(true);
        selectedChatLieu = dialog.selectedChatLieu;
        loadLabelSelected();
    }//GEN-LAST:event_btnChatLieuActionPerformed

    private void btnThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuongHieuActionPerformed
        Frame parentWindow = (Frame) SwingUtilities.windowForComponent(this);
        DialogThuongHieu dialog = new DialogThuongHieu(parentWindow, true);
        dialog.setVisible(true);
        selectedThuongHieu = dialog.selectedThuongHieu;
        loadLabelSelected();
    }//GEN-LAST:event_btnThuongHieuActionPerformed

    private void btnMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauActionPerformed
        Frame parentWindow = (Frame) SwingUtilities.windowForComponent(this);
        DialogMauSac dialog = new DialogMauSac(parentWindow, true);
        dialog.setVisible(true);
        selectedMau = dialog.selectedMauSac;
        loadLabelSelected();
    }//GEN-LAST:event_btnMauActionPerformed

    private void btnXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatXuActionPerformed
        Frame parentWindow = (Frame) SwingUtilities.windowForComponent(this);
        DialogXuatXu dialog = new DialogXuatXu(parentWindow, true);
        dialog.setVisible(true);
        selectedXuatXu = dialog.selectedXuatXu;
        loadLabelSelected();
    }//GEN-LAST:event_btnXuatXuActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        AoDTO dto = new AoDTO();
        SanPhamDTO spDTO = new SanPhamDTO();
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String moTa = txtMa.getText();
        float giaNhap = (float) spGiaNhap.getValue();
        float giaBan = (float) spGiaBan.getValue();
        int soLuong = (int) spSL.getValue();
        TrangThaiSanPham trangThai = TrangThaiSanPham.IN_ACTIVE;
        if (cbbTrangThai.getSelectedIndex() == 0){
            trangThai = TrangThaiSanPham.ACTIVE;
        }
        
        spDTO.setMaSP(ma);
        spDTO.setTenSP(ten);
        spDTO.setGiaNhap(giaNhap);
        spDTO.setGiaBan(giaBan);
        spDTO.setSoLuongTon(soLuong);
        spDTO.setMoTa(moTa);
        spDTO.setLoaiSp(LoaiSanPham.AO);
        spDTO.setTrangThaiSanPham(trangThai);
        spDTO.setMauSac(selectedMau);
        spDTO.setChatLieu(selectedChatLieu);
        spDTO.setThuongHieu(selectedThuongHieu);
        spDTO.setXuatXu(selectedXuatXu);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnKichCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKichCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKichCoActionPerformed

    private void loadLabelSelected() {
        lbXuatXu.setText(selectedXuatXu != null ? selectedXuatXu.getTen() : "");
        lbChatLieu.setText(selectedChatLieu != null ? selectedChatLieu.getTen() : "");
        lbMau.setText(selectedMau != null ? selectedMau.getTen() : "");
        lbThuongHieu.setText(selectedThuongHieu != null ? selectedThuongHieu.getTen() : "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.swing.Button btnChatLieu;
    private view.swing.Button btnHuy;
    private view.swing.Button btnKichCo;
    private view.swing.Button btnLuu;
    private view.swing.Button btnMau;
    private view.swing.Button btnThuongHieu;
    private view.swing.Button btnXuatXu;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbChatLieu;
    private javax.swing.JLabel lbKichCo;
    private javax.swing.JLabel lbMau;
    private javax.swing.JLabel lbThuongHieu;
    public javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbXuatXu;
    private javax.swing.JSpinner spGiaBan;
    private javax.swing.JSpinner spGiaNhap;
    private javax.swing.JSpinner spSL;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
